package com.cqut.atao.minic.miniC;
/* Generated By:JavaCC: Do not edit this line. MiniCTreeConstants.java Version 5.0 */


public interface MiniCTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTSTATEMENT = 2;
  public int JJTSTATEMENTBLOCKS = 3;
  public int JJTSEQSTATEMENT = 4;
  public int JJTDECLARSTATEMENT = 5;
  public int JJTASSIGNSTATEMENT = 6;
  public int JJTCONDSTATEMENT = 7;
  public int JJTLOGIC = 8;
  public int JJTLOGICAND = 9;
  public int JJTLOGICNOT = 10;
  public int JJTCONDITION = 11;
  public int JJTLOOPSTATEMENT = 12;
  public int JJTWHILE = 13;
  public int JJTDO_WHILE = 14;
  public int JJTFOR_LOOP = 15;
  public int JJTSWITCHCASE = 16;
  public int JJTEXPRESSION = 17;
  public int JJTADDITIVEEXPRESSION = 18;
  public int JJTMULTIPLICATIVEEXPRESSION = 19;
  public int JJTUNARYEXPRESSION = 20;
  public int JJTIDENTIFIER = 21;
  public int JJTINTEGER = 22;
  public int JJTFLOAT = 23;
  public int JJTSTARTKEY = 24;
  public int JJTDECLARKEY = 25;
  public int JJTRELATIONCHAR = 26;


  public String[] jjtNodeName = {
    "Start",
    "program",
    "Statement",
    "StatementBlocks",
    "SeqStatement",
    "DeclarStatement",
    "AssignStatement",
    "CondStatement",
    "Logic",
    "LogicAnd",
    "LogicNot",
    "Condition",
    "LoopStatement",
    "While",
    "Do_While",
    "For_Loop",
    "SwitchCase",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
    "Float",
    "StartKey",
    "DeclarKey",
    "RelationChar",
  };
}
/* JavaCC - OriginalChecksum=fe32113f2140ec43f177a2163e91c17b (do not edit this line) */
